
name: CI

on: [push, pull_request]

jobs:
        
  Cpp-Lint-WebKit:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: '.'
          extensions: 'h,cpp'
          clangFormatVersion: 10
          style: WebKit